# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-proteomicslfq-1.0dev

channels:
  - bgruening
  - conda-forge
  - bioconda
dependencies:
  - bgruening::openms
  - bioconda::thermorawfileparser
  - bioconda::msgf_plus
  - bioconda::comet-ms
  - bioconda::luciphor2
  - bioconda::percolator
  - bioconda::bioconductor-msstats=3.20.0 # will include R
  - bioconda::sdrf-pipelines # for SDRF conversion
  # TODO for release, pin to a version. For now, install in Dockerfile from github
  #- conda-forge::r-ptxqc # for QC reports
  - conda-forge::fonts-conda-ecosystem # for the fonts in QC reports
  - conda-forge::openjdk=8.* # pin java to 8 for MSGF (otherwise it somehow chooses 11)
  - conda-forge::python=3.8.1
  - conda-forge::markdown=3.2.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2

